import {spawn} from 'node:child_process';
import readline from 'node:readline';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
export class BridgeClient{
  constructor({timeoutMs=1500,watchdogMs=3000,mode='fake',onExit=()=>{}}={}){this.timeoutMs=timeoutMs;this.watchdogMs=watchdogMs;this.mode=mode;this.onExit=onExit;this.seq=0;this.pending=new Map();this.alive=false;this.pingTimer=null;this.latest=new Map();this.flushScheduled=false;this.dropped=0;this.operation=Promise.resolve()}
  start(){const native=this.mode==='native';const binary=native?(process.env.JOYLINKEA_DOTNET||'C:\\Program Files\\dotnet\\dotnet.exe'):process.execPath;const args=native?[resolve(root,'bridge/native/bin/Debug/net10.0-windows/JoyLinkBridge.dll'),'--run']:[resolve(root,'bridge/fake-bridge.js')];this.child=spawn(binary,args,{stdio:['pipe','pipe','inherit'],windowsHide:true,env:{...process.env,JOYLINKEA_BRIDGE_WATCHDOG_MS:String(this.watchdogMs)}});this.alive=true;readline.createInterface({input:this.child.stdout}).on('line',line=>{let r;try{r=JSON.parse(line)}catch{return}const p=this.pending.get(r.id);if(!p)return;clearTimeout(p.timer);this.pending.delete(r.id);r.ok?p.resolve(r):p.reject(Error(r.error||'BRIDGE_ERROR'))});this.child.on('exit',()=>{this.alive=false;clearInterval(this.pingTimer);for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('BRIDGE_EXIT'))}this.pending.clear();this.onExit()});this.pingTimer=setInterval(()=>this.command('PING').catch(()=>this.child.kill()),500);return this.command('PING')}
  command(type,payload={}){if(!this.alive)return Promise.reject(Error('BRIDGE_EXIT'));const id=++this.seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('BRIDGE_TIMEOUT'))},this.timeoutMs);this.pending.set(id,{resolve,reject,timer});const line=JSON.stringify({version:1,id,type,...payload})+'\n';if(Buffer.byteLength(line)>8192){clearTimeout(timer);this.pending.delete(id);reject(Error('BRIDGE_COMMAND_TOO_LARGE'));return}this.child.stdin.write(line,err=>{if(err){clearTimeout(timer);this.pending.delete(id);reject(err)}})})}
  enqueue(fn){const result=this.operation.then(fn);this.operation=result.catch(()=>{});return result}
  lifecycle(type,controllerId){this.latest.delete(controllerId);return this.enqueue(()=>this.command(type,{controllerId}))}
  state(controllerId,state){if(this.latest.has(controllerId))this.dropped++;this.latest.set(controllerId,state);this.scheduleFlush()}
  scheduleFlush(){if(this.flushScheduled)return;this.flushScheduled=true;this.enqueue(async()=>{const batch=[...this.latest];this.latest.clear();for(const [id,s] of batch)await this.command('SET_STATE',{controllerId:id,state:s});this.flushScheduled=false;if(this.latest.size)this.scheduleFlush()}).catch(()=>{this.flushScheduled=false;this.onExit()})}
  async stop(){clearInterval(this.pingTimer);if(!this.alive)return;try{await this.command('NEUTRALIZE_ALL');await this.command('SHUTDOWN')}catch{}if(this.child&&!this.child.killed)this.child.kill()}
}
