import {randomBytes,randomUUID} from 'node:crypto';
import {neutralState,isNeutral} from './gamepad.js';
const now=()=>performance.now();
export class Core{
 constructor(config,bridge,broadcast=()=>{}){this.config=config;this.bridge=bridge;this.broadcast=broadcast;this.sessions=new Map();this.credentials=new Map();this.sockets=new Map();this.closed=false;this.bridgeReady=false}
 snapshot(){const t=now();return {bridgeReady:this.bridgeReady,bridgeMode:this.config.bridge?.mode||'fake',slots:Array.from({length:this.config.players.max},(_,i)=>{const s=[...this.sessions.values()].find(x=>x.slot===i+1);return s?{slot:s.slot,sessionId:s.id,state:s.status,controllerId:s.slot,lastSeenMs:Math.round(t-s.lastSeen),inputAgeMs:s.lastInput?Math.round(t-s.lastInput):null,inputPerSecond:s.inputPerSecond,stale:s.stale,invalid:s.invalid,dropped:s.dropped,motion:s.motion,latency:s.latency,input:s.lastState}: {slot:i+1,state:'FREE'}})}}
 emit(){this.broadcast(this.snapshot())}
 send(ws,m){if(ws.readyState===1)ws.send(JSON.stringify(m))}
 async hello(ws,credential){if(this.closed||!this.bridgeReady)throw Error('BRIDGE_UNAVAILABLE');let s=credential?this.credentials.get(credential):null;if(credential&&!s)throw Error('INVALID_CREDENTIAL');if(s&&s.status==='EXPIRED')throw Error('SESSION_EXPIRED');if(!s){const used=new Set([...this.sessions.values()].map(x=>x.slot));const slot=Array.from({length:this.config.players.max},(_,i)=>i+1).find(x=>!used.has(x));if(!slot)throw Error('NO_SLOT');s={id:randomUUID(),slot,credential:'',generation:0,ws:null,status:'CONNECTING',lastSeen:now(),lastInput:0,lastSeq:-1,lastState:neutralState(),inputPerSecond:0,inputWindowAt:now(),inputCount:0,stale:0,invalid:0,dropped:0,motion:null,latency:null,graceDeadline:0,neutralized:false};this.sessions.set(s.id,s);try{await this.bridge.lifecycle('CREATE_CONTROLLER',slot)}catch(e){this.sessions.delete(s.id);throw e}}
  if(s.ws&&s.ws!==ws){this.sockets.delete(s.ws);try{s.ws.close()}catch{}}
  if(s.credential)this.credentials.delete(s.credential);s.credential=randomBytes(24).toString('base64url');this.credentials.set(s.credential,s);s.generation++;s.ws=ws;s.status='CONNECTED';s.lastSeen=now();s.lastInput=0;s.lastSeq=-1;s.lastState=neutralState();s.neutralized=false;this.sockets.set(ws,s);await this.bridge.lifecycle('NEUTRALIZE',s.slot);this.send(ws,{type:'WELCOME',version:1,sessionId:s.id,resumeCredential:s.credential,slot:s.slot,generation:s.generation,bridgeMode:this.config.bridge?.mode||'fake',sendRateHz:this.config.input.sendRateHz,deadzone:this.config.input.deadzone,heartbeatIntervalMs:this.config.network.heartbeatIntervalMs,latencySampleIntervalMs:this.config.latency.sampleIntervalMs,motionEnabled:this.config.motion.enabled});this.emit();return s}
 async lost(ws,leave=false){const s=this.sockets.get(ws);if(!s)return;this.sockets.delete(ws);if(s.ws!==ws)return;s.ws=null;s.status='GRACE';s.lastState=neutralState();s.graceDeadline=now()+(leave?0:this.config.network.reconnectGraceMs);await this.bridge.lifecycle('NEUTRALIZE',s.slot).catch(()=>{});this.emit()}
 input(ws,m){const s=this.sockets.get(ws);if(!s||s.ws!==ws||s.status!=='CONNECTED')return 'UNAUTHORIZED';if(m.seq<=s.lastSeq){s.stale++;return 'STALE'}s.lastSeq=m.seq;s.lastInput=now();s.lastSeen=s.lastInput;s.lastState=m.state;s.neutralized=false;s.inputCount++;if(s.lastInput-s.inputWindowAt>=1000){s.inputPerSecond=Math.round(s.inputCount*1000/(s.lastInput-s.inputWindowAt));s.inputWindowAt=s.lastInput;s.inputCount=0}this.bridge.state(s.slot,m.state);s.dropped=this.bridge.dropped;this.emit();return 'OK'}
 heartbeat(ws){const s=this.sockets.get(ws);if(s&&s.ws===ws)s.lastSeen=now()}
 latency(ws,m){const s=this.sockets.get(ws);if(s&&s.ws===ws){s.latency={last:m.last,smooth:m.smooth,jitter:m.jitter};this.emit()}}
 motion(ws,state){const s=this.sockets.get(ws);if(s&&s.ws===ws&&this.config.motion.enabled){s.motion=state;this.emit()}}
 async tick(){const t=now();for(const s of [...this.sessions.values()]){if(s.status==='CONNECTED'){if(t-s.lastSeen>this.config.network.heartbeatTimeoutMs){try{s.ws?.close()}catch{}await this.lost(s.ws)}else if(s.lastInput&&!isNeutral(s.lastState)&&t-s.lastInput>this.config.input.stateTimeoutMs&&!s.neutralized){s.neutralized=true;s.lastState=neutralState();await this.bridge.lifecycle('NEUTRALIZE',s.slot).catch(()=>{});this.emit()}}else if(s.status==='GRACE'&&t>=s.graceDeadline){await this.bridge.lifecycle('NEUTRALIZE',s.slot).catch(()=>{});await this.bridge.lifecycle('DESTROY_CONTROLLER',s.slot).catch(()=>{});this.credentials.delete(s.credential);this.sessions.delete(s.id);this.emit()}}}
 bridgeExit(){if(!this.bridgeReady)return;this.bridgeReady=false;for(const s of this.sessions.values()){s.status='ERROR';s.lastState=neutralState();s.ws&&this.send(s.ws,{type:'STATUS',state:'BRIDGE_ERROR'})}this.emit()}
 async shutdown(){if(this.closed)return;this.closed=true;for(const s of this.sessions.values())s.lastState=neutralState();await this.bridge.command('NEUTRALIZE_ALL').catch(()=>{});for(const s of this.sessions.values())await this.bridge.lifecycle('DESTROY_CONTROLLER',s.slot).catch(()=>{});this.sessions.clear();this.credentials.clear();this.emit();await this.bridge.stop()}
}
